Interactive treemap for fossil fuel page (#178)
* Skeleton for Company Emission Query

* Aggregation query that returns the emissions per company. This will be
  called by the Treemap Chart component, which will then need to format
the return from this into a digestable for from for the apexchat treemap

* Updating Company Schema with Market Cap

* Implemented Treemap Query

* getEmissionsAndFFClass returns the financed emissions and
  classification of each company, which will be used by the tree map in
grouping (fossil fuel vs non-fossil fuel)

* In the future, I would like to add a carbon underground
  classification, but this is MVP

* Treemap is almost there, onto debugging

Primary bug to handle

* Error converting field "market_cap" of expected non-nullable type "Float", found incompatible value of "null".

* Debugging Treemap

Resolved nonnullable flast marketcap error by changing market_cap to
'Float?' in schema.

Now running into the error
* Unhandled Runtime Error
  TypeError: Cannot read properties of undefined (reading 'length')

* Got treemap to work, now we need to make pretty

We now have a treemap that displays the right information, we just need
to make it look good and understandable

* update market_cap to marketCap

* Made Treemap Pretty

* treemap now takes up 3/4 of width of the page
* shades are disabled on the treemap for a uniform look

* OnClick, chart opens company page

Right now, we open the url
	const url =`https://www.toriis.earth/company/${companyId ?? ''}`
Is there a safer way to do this?

* Disabled shading treemap box shading on click

changed the active state filter to none in options to disable shading on
click

* Made Chart Pretty

* Added legend
* Removed xaxis tick marks

* Update src/components/Charts/EmissionTreeMap.tsx

Co-authored-by: Zora Zhang <zorazrr@gmail.com>

* Update src/components/Charts/EmissionTreeMap.tsx

Using `?` operator for pre-checking

Co-authored-by: Zora Zhang <zorazrr@gmail.com>

* Update src/components/Charts/EmissionTreeMap.tsx

Pre-checking with `?` operator

Co-authored-by: Zora Zhang <zorazrr@gmail.com>

* Update src/server/api/routers/company.ts

Co-authored-by: Zora Zhang <zorazrr@gmail.com>

* Use of generics for SourceData

Updating code to use generics so for clean and readable code.

* Add formatSeries helper

Restructered code to have `formatSeries` helper so that code is more
readable

* Grabbing Industry Enums from dm/dynamic-table

* For use in src/server/api/routers/company.ts

* Use industryEnum to determine fossilFuelClass

* Removed unessesary comment

* Removed unnessesary null check

* Made `FOSSIL_FUEL_INDUSTRIES` constant

* adds `FOSSIL_FUEL_INDUSTRIES` array in `constants.ts`
* cleans up code in company.ts
* romves need for an `INDUSTRIES_ENUM` in `enums.ts`

* Added `BASE_URL` constant

This is needed in the case that we change our domain name.

* Removed need for BASE_URL constant

window.open knows BASE_URL so the constant was redundant

---------

Co-authored-by: kennykos <“gkosmacher01@gmail.com”>
Co-authored-by: Zora Zhang <zorazrr@gmail.com>